# Change these first
owner: SparksTheFolf # Your GitHub organization or username, where this repository lives
repo: STF-Uptime-Status # The name of this repository

sites:
  - name: Wuffs Main
    url: https://wuffs.net/
  - name: Blog
    url: https://blog.trpn.dev
  - name: HMS Authority Issuance Server
    check: "tcp-ping"
    url: $HMS_CA_AUTHORITY
    port: 22
  - name: HMS Authority Frontend Server
    check: "tcp-ping"
    url: $HMS_CA_FRONTEND
    port: 22
  
status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wuffs.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/SparksTheFolf/STF-Uptime-Status/master/logo.JPG
  name: Sparks Uptime
  introTitle: "This is an uptime status for all bots and websites."
  introMessage: Any included here below is part of my global CDN infrastructure hosted by Cloudflare.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://blog.trpn.dev
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
